// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package demo.auto.gen;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public class Rc {


    /*package*/ final int mA;

    public Rc(
            int a) {
        this.mA = a;
    }

    public int getA() {
        return mA;
    }

    @Override
    public String toString() {
        return "Rc{" +
                "mA=" + mA +
        "}";
    }

}
