// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <DJIMarshal+Private.h>
#import "MyRecord+Private.h"
#import <DJIMarshal+Json.h>
#include <cassert>

namespace djinni_generated {

auto MyRecordHelper::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.id)};
}

auto MyRecordHelper::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[MyRecord alloc] initWithId:(::djinni::I32::fromCpp(cpp.id))];
}

}  // namespace djinni_generated
