// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <DjinniExample/DjinniExample-Swift.h>
#include "a.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class A;

namespace djinni_generated {

struct AHelper
{
    using CppType = ::textsort::A;
    using ObjcType = A*;

    using Boxed = AHelper;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
