// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "A+Private.h"
#import <Djinni/DJIMarshal+Json.h>
#import <Djinni/DJIMarshal+Private.h>
#include <cassert>

namespace djinni_generated {

auto AHelper::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::U8::toCpp(obj.__djinni__objc_h)};
}

auto AHelper::fromCpp(const CppType& cpp) -> ObjcType
{
    return [A initWithH:(::djinni::U8::fromCpp(cpp.h))];
}

}  // namespace djinni_generated
