// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "JsonRecord+Private.h"
#import "Rc+Private.h"
#import <Djinni/DJIMarshal+Json.h>
#import <Djinni/DJIMarshal+Private.h>
#include <cassert>

namespace djinni_generated {

auto JsonRecordHelper::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::Optional<std::optional, ::djinni_generated::RcHelper>::toCpp(obj.__djinni__objc_optionalRc)};
}

auto JsonRecordHelper::fromCpp(const CppType& cpp) -> ObjcType
{
    return [JsonRecord initWithOptionalRc:(::djinni::Optional<std::optional, ::djinni_generated::RcHelper>::fromCpp(cpp.optional_rc))];
}

}  // namespace djinni_generated
