// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <DjinniExample/DjinniExample-Swift.h>
#include "my_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class MyRecord;

namespace djinni_generated {

struct MyRecordHelper
{
    using CppType = ::textsort::MyRecord;
    using ObjcType = MyRecord*;

    using Boxed = MyRecordHelper;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
