// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "Rc+Private.h"
#import "MyEnum+Private.h"
#import <Djinni/DJIMarshal+Json.h>
#import <Djinni/DJIMarshal+Private.h>
#include <cassert>

namespace djinni_generated {

auto RcHelper::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.__djinni__objc_a),
            ::djinni::I32::toCpp(obj.__djinni__objc_b),
            ::djinni::Optional<std::optional, ::djinni::I32>::toCpp(obj.__djinni__objc_c),
            ::djinni::Enum<::textsort::my_enum, MyEnum>::toCpp(obj.__djinni__objc_d),
            ::djinni::Binary::toCpp(obj.__djinni__objc_e)};
}

auto RcHelper::fromCpp(const CppType& cpp) -> ObjcType
{
    return [Rc initWithA:(::djinni::I32::fromCpp(cpp.a))
                       b:(::djinni::I32::fromCpp(cpp.b))
                       c:(::djinni::Optional<std::optional, ::djinni::I32>::fromCpp(cpp.c))
                       d:(::djinni::Enum<::textsort::my_enum, MyEnum>::fromCpp(cpp.d))
                       e:(::djinni::Binary::fromCpp(cpp.e))];
}

}  // namespace djinni_generated
