// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "Rc+Private.h"
#import <Djinni/DJIMarshal+Json.h>
#import <Djinni/DJIMarshal+Private.h>
#include <cassert>

namespace djinni_generated {

auto RcHelper::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::I32::toCpp(obj.__djinni__objc_a)};
}

auto RcHelper::fromCpp(const CppType& cpp) -> ObjcType
{
    return [Rc initWithA:(::djinni::I32::fromCpp(cpp.a))];
}

}  // namespace djinni_generated
