// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <DJIMarshal+Private.h>
#import "TXSBaseRecord+Private.h"
#import <DJIMarshal+Json.h>
#include <cassert>

namespace djinni_generated {

auto BaseRecordHelper::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.hien),
            ::djinni::String::toCpp(obj.hien1),
            ::djinni::String::toCpp(obj.parent)};
}

auto BaseRecordHelper::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSBaseRecord alloc] initWithHien:(::djinni::String::fromCpp(cpp.hien))
                                         hien1:(::djinni::String::fromCpp(cpp.hien_1))
                                        parent:(::djinni::String::fromCpp(cpp.parent))];
}

}  // namespace djinni_generated
