// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

#import "TXSHien.h"
NS_SWIFT_NAME(BaseRecord)
@interface TXSBaseRecord : TXSHien
- (nonnull instancetype)initWithHien:(nonnull NSString *)hien
                               hien1:(nonnull NSString *)hien1
                              parent:(nonnull NSString *)parent;
+ (nonnull instancetype)baseRecordWithHien:(nonnull NSString *)hien
                                     hien1:(nonnull NSString *)hien1
                                    parent:(nonnull NSString *)parent;

@property (nonatomic, readonly, nonnull) NSString * parent;

@end
