// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSBaseRecord.h"
#include "base_record.hpp"

static_assert(__has_feature(objc_arc), "Djinni requires ARC to be enabled for this file");

@class TXSBaseRecord;

namespace djinni_generated {

struct BaseRecordHelper
{
    using CppType = ::textsort::BaseRecord;
    using ObjcType = TXSBaseRecord*;

    using Boxed = BaseRecordHelper;

    static CppType toCpp(ObjcType objc);
    static ObjcType fromCpp(const CppType& cpp);
};

}  // namespace djinni_generated
