// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSBaseRecord.h"


@implementation TXSBaseRecord

- (nonnull instancetype)initWithHien:(nonnull NSString *)hien
                               hien1:(nonnull NSString *)hien1
                              parent:(nonnull NSString *)parent
{
    if (self = [super initWithHien:hien
                             hien1:hien1])
    {
        _parent = [parent copy];
    }
    return self;
}

+ (nonnull instancetype)baseRecordWithHien:(nonnull NSString *)hien
                                     hien1:(nonnull NSString *)hien1
                                    parent:(nonnull NSString *)parent
{
    return [(TXSBaseRecord*)[self alloc] initWithHien:hien
                                                hien1:hien1
                                               parent:parent];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p hien:%@ hien1:%@ parent:%@>", self.class, (void *)self, self.hien, self.hien1, self.parent];
}

@end
