// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

NS_SWIFT_NAME(Hien)
@interface TXSHien : NSObject
- (nonnull instancetype)initWithHien:(nonnull NSString *)hien
                               hien1:(nonnull NSString *)hien1;
+ (nonnull instancetype)hienWithHien:(nonnull NSString *)hien
                               hien1:(nonnull NSString *)hien1;

@property (nonatomic, readonly, nonnull) NSString * hien;

@property (nonatomic, readonly, nonnull) NSString * hien1;

@end
