// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <DJIMarshal+Private.h>
#import "TXSHien+Private.h"
#import <DJIMarshal+Json.h>
#include <cassert>

namespace djinni_generated {

auto HienHelper::toCpp(ObjcType obj) -> CppType
{
    assert(obj);
    return {::djinni::String::toCpp(obj.hien),
            ::djinni::String::toCpp(obj.hien1)};
}

auto HienHelper::fromCpp(const CppType& cpp) -> ObjcType
{
    return [[TXSHien alloc] initWithHien:(::djinni::String::fromCpp(cpp.hien))
                                   hien1:(::djinni::String::fromCpp(cpp.hien_1))];
}

}  // namespace djinni_generated
