// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSHien.h"


@implementation TXSHien

- (nonnull instancetype)initWithHien:(nonnull NSString *)hien
                               hien1:(nonnull NSString *)hien1
{
    if (self = [super init]) {
        _hien = [hien copy];
        _hien1 = [hien1 copy];
    }
    return self;
}

+ (nonnull instancetype)hienWithHien:(nonnull NSString *)hien
                               hien1:(nonnull NSString *)hien1
{
    return [(TXSHien*)[self alloc] initWithHien:hien
                                          hien1:hien1];
}

- (NSString *)description
{
    return [NSString stringWithFormat:@"<%@ %p hien:%@ hien1:%@>", self.class, (void *)self, self.hien, self.hien1];
}

@end
