// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

NS_SWIFT_NAME(ItemList)
@interface TXSItemList : NSObject
- (nonnull instancetype)initWithItems:(nonnull NSArray<NSString *> *)items;
+ (nonnull instancetype)itemListWithItems:(nonnull NSArray<NSString *> *)items;

@property (nonatomic, nonnull) NSArray<NSString *> * items;

@end
