// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, TXSSortOrder)
{
    TXSSortOrderAscending = 1,
    TXSSortOrderDescending = 3,
    TXSSortOrderRandom,
} NS_SWIFT_NAME(SortOrder);
