// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import "TXSItemList.h"
#import <Foundation/Foundation.h>


NS_SWIFT_NAME(TextboxListener)
@protocol TXSTextboxListener

- (void)update:(nonnull TXSItemList *)items;

@end
