// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "NativeHien.hpp"  // my header
#include "JNIMarshal+Json.h"
#include "Marshal.hpp"

namespace djinni_generated {

NativeHien::NativeHien() = default;

NativeHien::~NativeHien() = default;

auto NativeHien::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeHien>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.hien)),
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.hien_1)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeHien::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 3);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeHien>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mHien)),
            ::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mHien1))};
}

}  // namespace djinni_generated
