// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "NativeBaseRecord.hpp"  // my header
#include "JNIMarshal+Json.h"
#include "Marshal.hpp"

namespace djinni_generated {

NativeBaseRecord::NativeBaseRecord() = default;

NativeBaseRecord::~NativeBaseRecord() = default;

auto NativeBaseRecord::fromCpp(JNIEnv* jniEnv, const CppType& c) -> ::djinni::LocalRef<JniType> {
    const auto& data = ::djinni::JniClass<NativeBaseRecord>::get();
    auto r = ::djinni::LocalRef<JniType>{jniEnv->NewObject(data.clazz.get(), data.jconstructor,
                                                           ::djinni::get(::djinni::String::fromCpp(jniEnv, c.parent)))};
    ::djinni::jniExceptionCheck(jniEnv);
    return r;
}

auto NativeBaseRecord::toCpp(JNIEnv* jniEnv, JniType j) -> CppType {
    ::djinni::JniLocalScope jscope(jniEnv, 2);
    assert(j != nullptr);
    const auto& data = ::djinni::JniClass<NativeBaseRecord>::get();
    return {::djinni::String::toCpp(jniEnv, (jstring)jniEnv->GetObjectField(j, data.field_mParent))};
}

}  // namespace djinni_generated
