// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "djinni_support.hpp"
#include "json_record.hpp"

namespace djinni_generated {

class NativeJsonRecord final {
public:
    using CppType = ::textsort::JsonRecord;
    using JniType = jobject;

    using Boxed = NativeJsonRecord;

    ~NativeJsonRecord();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeJsonRecord();
    friend ::djinni::JniClass<NativeJsonRecord>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/textsort/JsonRecord") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Lcom/dropbox/textsort/Rc;)V") };
    const jfieldID field_mOptionalRc { ::djinni::jniGetFieldID(clazz.get(), "mOptionalRc", "Lcom/dropbox/textsort/Rc;") };
};

}  // namespace djinni_generated
