// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "a.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeA final {
public:
    using CppType = ::textsort::A;
    using JniType = jobject;

    using Boxed = NativeA;

    ~NativeA();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeA();
    friend ::djinni::JniClass<NativeA>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/textsort/A") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(S)V") };
    const jfieldID field_mH { ::djinni::jniGetFieldID(clazz.get(), "mH", "S") };
};

}  // namespace djinni_generated
