// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "djinni_support.hpp"
#include "hello.hpp"

namespace djinni_generated {

class NativeHello final : ::djinni::JniInterface<::textsort::Hello, NativeHello> {
public:
    using CppType = std::shared_ptr<::textsort::Hello>;
    using CppOptType = std::shared_ptr<::textsort::Hello>;
    using JniType = jobject;

    using Boxed = NativeHello;

    ~NativeHello();

    static CppType toCpp(JNIEnv* jniEnv, JniType j) { return ::djinni::JniClass<NativeHello>::get()._fromJava(jniEnv, j); }
    static ::djinni::LocalRef<JniType> fromCppOpt(JNIEnv* jniEnv, const CppOptType& c) { return {jniEnv, ::djinni::JniClass<NativeHello>::get()._toJava(jniEnv, c)}; }
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c) { return fromCppOpt(jniEnv, c); }

private:
    NativeHello();
    friend ::djinni::JniClass<NativeHello>;
    friend ::djinni::JniInterface<::textsort::Hello, NativeHello>;

};

}  // namespace djinni_generated
