// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package demo.auto.gen;

import androidx.annotation.NonNull;
import androidx.annotation.Nullable;

public enum MyEnum {
    HIEN(1),
    A(2),
    B(3),
    ;
    private final int value;
    private MyEnum(int value) {
        this.value = value;
    }
    public int getValue() {
        return this.value;
    }
}
