// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <memory>

namespace demo {

enum class my_enum;
struct MyRecord;

class Hello {
public:
    virtual ~Hello() {}

    static std::shared_ptr<Hello> create();

    virtual void hlll() = 0;

    virtual MyRecord say_hello(my_enum e) = 0;

    virtual my_enum say_hi() = 0;
};

}  // namespace demo
