// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <functional>

namespace demo {

enum class  my_enum : int {
    HIEN ,
    A ,
    B ,
};

}  // namespace demo

namespace std {

template <>
struct hash<::demo::my_enum> {
    size_t operator()(::demo::my_enum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
