// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace demo {

struct  MyRecord {
    int32_t id;

    MyRecord(int32_t id_)
    : id(std::move(id_))
    {}
};

}  // namespace demo
