// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "my_record.hpp"
#include <string>
#include <utility>

namespace textsort {

struct  SubRecrod : MyRecord {
    std::string hien;

    SubRecrod(int32_t id_,
              std::optional<std::string> info_,
              std::vector<std::string> l1_,
              std::string hien_)
    : 
    MyRecord( id_,
              info_,
              l1_), hien(std::move(hien_)){}
};

}  // namespace textsort
