// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace textsort {

struct  A {
    uint8_t h;

    A(uint8_t h_)
    : h(std::move(h_))
    {}

    A() = default;
};

}  // namespace textsort
