// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "hien.hpp"
#include <string>
#include <utility>

namespace textsort {

struct  BaseRecord : Hien {
    std::string parent;

    BaseRecord(std::string hien_,
               std::string hien_1_,
               std::string parent_)
    : 
    Hien( hien_,
          hien_1_), parent(std::move(parent_)){}
};

}  // namespace textsort
