// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <memory>

namespace cpp_generated {

enum class MyEnum;
struct MyRecord;

class Hello {
public:
    virtual ~Hello() {}

    static std::shared_ptr<Hello> create();

    virtual MyEnum say_hi() = 0;

    virtual MyRecord print(const MyRecord & rc) = 0;
};

}  // namespace cpp_generated
