// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <memory>

namespace textsort {

enum class my_enum;
struct MyRecord;

class Hello {
public:
    virtual ~Hello() {}

    static std::shared_ptr<Hello> create();

    virtual my_enum say_hi() = 0;

    virtual MyRecord print(const MyRecord & rc) = 0;
};

}  // namespace textsort
