// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <string>
#include <utility>

namespace textsort {

struct  Hien {
    std::string hien;
    std::string hien_1;

    Hien(std::string hien_,
         std::string hien_1_)
    : hien(std::move(hien_))
    , hien_1(std::move(hien_1_))
    {}
};

}  // namespace textsort
