// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include "json_record.hpp"  // my header
#include <sstream>

namespace textsort {


}  // namespace textsort
