// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <functional>

namespace textsort {

enum class my_enum : int {
    HIEN  = 1,
    WORKOUT ,
    RUNNING ,
};

}  // namespace textsort

namespace std {

template <>
struct hash<::textsort::my_enum> {
    size_t operator()(::textsort::my_enum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
