// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "my_enum.hpp"
#include "rc.hpp"
#include <chrono>
#include <cstdint>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace textsort {

struct  MyRecord {
    int32_t test;
    std::optional<uint32_t> test1;
    std::vector<uint32_t> test2;
    std::string test3;
    std::optional<std::string> test3_1;
    std::chrono::system_clock::time_point test4;
    std::optional<std::chrono::system_clock::time_point> test4_1;
    std::vector<uint8_t> test5;
    std::vector<std::vector<uint8_t>> test6;
    std::unordered_set<int32_t> test7;
    std::unordered_map<int32_t, std::string> test8;
    Rc test9;
    std::optional<Rc> test10;
    std::vector<Rc> test10_1;
    my_enum test11;
    std::optional<my_enum> test13;
    std::optional<int16_t> test14;
    std::vector<my_enum> test15;
    std::unordered_set<my_enum> test16;
    std::unordered_map<my_enum, int16_t> test17;

    MyRecord(int32_t test_,
             std::optional<uint32_t> test1_,
             std::vector<uint32_t> test2_,
             std::string test3_,
             std::optional<std::string> test3_1_,
             std::chrono::system_clock::time_point test4_,
             std::optional<std::chrono::system_clock::time_point> test4_1_,
             std::vector<uint8_t> test5_,
             std::vector<std::vector<uint8_t>> test6_,
             std::unordered_set<int32_t> test7_,
             std::unordered_map<int32_t, std::string> test8_,
             Rc test9_,
             std::optional<Rc> test10_,
             std::vector<Rc> test10_1_,
             my_enum test11_,
             std::optional<my_enum> test13_,
             std::optional<int16_t> test14_,
             std::vector<my_enum> test15_,
             std::unordered_set<my_enum> test16_,
             std::unordered_map<my_enum, int16_t> test17_)
    : test(std::move(test_))
    , test1(std::move(test1_))
    , test2(std::move(test2_))
    , test3(std::move(test3_))
    , test3_1(std::move(test3_1_))
    , test4(std::move(test4_))
    , test4_1(std::move(test4_1_))
    , test5(std::move(test5_))
    , test6(std::move(test6_))
    , test7(std::move(test7_))
    , test8(std::move(test8_))
    , test9(std::move(test9_))
    , test10(std::move(test10_))
    , test10_1(std::move(test10_1_))
    , test11(std::move(test11_))
    , test13(std::move(test13_))
    , test14(std::move(test14_))
    , test15(std::move(test15_))
    , test16(std::move(test16_))
    , test17(std::move(test17_))
    {}

    MyRecord() = default;
};

}  // namespace textsort
