// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <cstdint>
#include <utility>

namespace cpp_generated {

struct  Rc {
    int32_t a;

    Rc(int32_t a_)
    : a(std::move(a_))
    {}

    Rc() = default;
};

}  // namespace cpp_generated
