// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>
@class MyRecord;
#import "MyEnum.h"
@class Hello;


NS_SWIFT_NAME(Hello)
@interface Hello : NSObject

- (nonnull instancetype)init NS_UNAVAILABLE;

+ (nullable Hello *)create;

- (void)hlll;

- (nonnull MyRecord *)sayHello:(MyEnum)e;

- (MyEnum)sayHi;

@end
