// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import Foundation

@objc public class MyRecord : NSObject {

    @objc public let id : Int32

    @objc public init(id:Int32) {
        self.id = id
    }
}
