// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

struct DjinniWrapperHello;
void hello___wrapper_dec_ref(struct DjinniWrapperHello * dh);
void hello___wrapper_add_ref(struct DjinniWrapperHello * dh);

struct DjinniWrapperHello * cw__hello_create(void);

int cw__hello_say_hi(struct DjinniWrapperHello * djinni_this);

struct DjinniRecordHandle * cw__hello_print(struct DjinniWrapperHello * djinni_this, struct DjinniRecordHandle * rc);

