// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdint.h> // python_cdef_ignore

struct DjinniMyRecord;
void my_record___delete(struct DjinniRecordHandle * );
void optional_my_record___delete(struct DjinniOptionalRecordHandle * );
void my_record_add_callback_get_my_record_f1(int32_t( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f2(struct DjinniBoxedI32 *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f3(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f4(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f5(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f6(uint64_t( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f7(struct DjinniBoxedDate *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f8(struct DjinniBinary *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f9(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f10(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f11(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f12(struct DjinniRecordHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f13(struct DjinniOptionalRecordHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f14(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f15(int( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f16(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f17(int( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f18(struct DjinniBoxedI16 *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f19(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f20(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_get_my_record_f21(struct DjinniObjectHandle *( * ptr)(struct DjinniRecordHandle *));
void my_record_add_callback_python_create_my_record(struct DjinniRecordHandle *( * ptr)(int32_t, struct DjinniBoxedI32 *, struct DjinniObjectHandle *, struct DjinniString *, struct DjinniString *, uint64_t, struct DjinniBoxedDate *, struct DjinniBinary *, struct DjinniObjectHandle *, struct DjinniObjectHandle *, struct DjinniObjectHandle *, struct DjinniRecordHandle *, struct DjinniOptionalRecordHandle *, struct DjinniObjectHandle *, int, struct DjinniString *, int, struct DjinniBoxedI16 *, struct DjinniObjectHandle *, struct DjinniObjectHandle *, struct DjinniObjectHandle *));
void my_record_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
