// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "hello.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "cw__hello.h"

#ifdef __cplusplus
}
#endif
struct DjinniWrapperHello final {
    DjinniWrapperHello(std::shared_ptr<::cpp_generated::Hello>wo): wrapped_obj(wo) {};

    static std::shared_ptr<::cpp_generated::Hello> get(djinni::Handle<DjinniWrapperHello> dw);
    static djinni::Handle<DjinniWrapperHello> wrap(std::shared_ptr<::cpp_generated::Hello> obj);

    const std::shared_ptr<::cpp_generated::Hello> wrapped_obj;
    std::atomic<size_t> ref_count {1};
};
