// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "my_record.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__map_enum_my_enum_int16_t.h"

#ifdef __cplusplus
}
#endif
struct DjinniMapEnumMyEnumInt16T {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::unordered_map<::textsort::my_enum, int16_t> & dc);
    static std::unordered_map<::textsort::my_enum, int16_t> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::optional<std::unordered_map<::textsort::my_enum, int16_t>> dc);
    static std::optional<std::unordered_map<::textsort::my_enum, int16_t>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
