// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "json_record.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__json_record.h"

#ifdef __cplusplus
}
#endif
struct DjinniJsonRecord {
    static djinni::Handle<DjinniRecordHandle> fromCpp(const ::textsort::JsonRecord& dr);
    static ::textsort::JsonRecord toCpp(djinni::Handle<DjinniRecordHandle> dh);
    static djinni::Handle<DjinniOptionalRecordHandle> fromCpp(std::optional<::textsort::JsonRecord> dc);
    static std::optional<::textsort::JsonRecord> toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh);
};
