// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "base_record.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__base_record.h"

#ifdef __cplusplus
}
#endif
struct DjinniBaseRecord {
    static djinni::Handle<DjinniRecordHandle> fromCpp(const ::textsort::BaseRecord& dr);
    static ::textsort::BaseRecord toCpp(djinni::Handle<DjinniRecordHandle> dh);
    static djinni::Handle<DjinniOptionalRecordHandle> fromCpp(std::experimental::optional<::textsort::BaseRecord> dc);
    static std::experimental::optional<::textsort::BaseRecord> toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh);
};
