// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <experimental/optional>
#include "hien.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__hien.h"

#ifdef __cplusplus
}
#endif
struct DjinniHien {
    static djinni::Handle<DjinniRecordHandle> fromCpp(const ::textsort::Hien& dr);
    static ::textsort::Hien toCpp(djinni::Handle<DjinniRecordHandle> dh);
    static djinni::Handle<DjinniOptionalRecordHandle> fromCpp(std::experimental::optional<::textsort::Hien> dc);
    static std::experimental::optional<::textsort::Hien> toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh);
};
