// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "my_record.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__list_enum_my_enum.h"

#ifdef __cplusplus
}
#endif
struct DjinniListEnumMyEnum {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::vector<::textsort::my_enum> & dc);
    static std::vector<::textsort::my_enum> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::optional<std::vector<::textsort::my_enum>> dc);
    static std::optional<std::vector<::textsort::my_enum>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
