// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "my_record.hpp"

#include "dh__list_binary.hpp"
#include "dh__list_enum_my_enum.hpp"
#include "dh__list_int32_t.hpp"
#include "dh__list_record_rc.hpp"
#include "dh__map_enum_my_enum_int16_t.hpp"
#include "dh__map_int32_t_string.hpp"
#include "dh__my_enum.hpp"
#include "dh__my_record.hpp"
#include "dh__rc.hpp"
#include "dh__set_enum_my_enum.hpp"
#include "dh__set_int32_t.hpp"
#include "my_enum.hpp"
#include <chrono>
#include <optional>
#include <vector>

static void(*s_py_callback_map_int32_t_string___delete)(DjinniObjectHandle *);
void map_int32_t_string_add_callback___delete(void(* ptr)(DjinniObjectHandle *)) {
    s_py_callback_map_int32_t_string___delete = ptr;
}

void map_int32_t_string___delete(DjinniObjectHandle * drh) {
    s_py_callback_map_int32_t_string___delete(drh);
}
void optional_map_int32_t_string___delete(DjinniOptionalObjectHandle *  drh) {
    s_py_callback_map_int32_t_string___delete((DjinniObjectHandle *) drh);
}
static DjinniString * ( * s_py_callback_map_int32_t_string__get_value)(DjinniObjectHandle *, int32_t);

void map_int32_t_string_add_callback__get_value(DjinniString *( * ptr)(DjinniObjectHandle *, int32_t)) {
    s_py_callback_map_int32_t_string__get_value = ptr;
}

static size_t ( * s_py_callback_map_int32_t_string__get_size)(DjinniObjectHandle *);

void map_int32_t_string_add_callback__get_size(size_t( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_map_int32_t_string__get_size = ptr;
}

static DjinniObjectHandle * ( * s_py_callback_map_int32_t_string__python_create)(void);

void map_int32_t_string_add_callback__python_create(DjinniObjectHandle *( * ptr)(void)) {
    s_py_callback_map_int32_t_string__python_create = ptr;
}

static void ( * s_py_callback_map_int32_t_string__python_add)(DjinniObjectHandle *, int32_t, DjinniString *);

void map_int32_t_string_add_callback__python_add(void( * ptr)(DjinniObjectHandle *, int32_t, DjinniString *)) {
    s_py_callback_map_int32_t_string__python_add = ptr;
}

static int32_t ( * s_py_callback_map_int32_t_string__python_next)(DjinniObjectHandle *);

void map_int32_t_string_add_callback__python_next(int32_t( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_map_int32_t_string__python_next = ptr;
}

djinni::Handle<DjinniObjectHandle> DjinniMapInt32TString::fromCpp(const std::unordered_map<int32_t, std::string> & dc) {
    djinni::Handle<DjinniObjectHandle> _handle(s_py_callback_map_int32_t_string__python_create(), & map_int32_t_string___delete);
    for (const auto & it : dc) {
        auto _val = DjinniString::fromCpp(it.second);
        s_py_callback_map_int32_t_string__python_add(_handle.get(), it.first, _val.release());
    }

    return _handle;
}

std::unordered_map<int32_t, std::string> DjinniMapInt32TString::toCpp(djinni::Handle<DjinniObjectHandle> dh) {
    std::unordered_map<int32_t, std::string>_ret;
    size_t size = s_py_callback_map_int32_t_string__get_size(dh.get());

    for (int i = 0; i < size; i++) {
        auto _key_c = s_py_callback_map_int32_t_string__python_next(dh.get()); // key that would potentially be surrounded by unique pointer
        auto _val = DjinniString::toCpp(std::unique_ptr<DjinniString>(s_py_callback_map_int32_t_string__get_value(dh.get(), _key_c)));

        auto _key = _key_c;
        _ret.emplace(std::move(_key), std::move(_val));
    }

    return _ret;
}

djinni::Handle<DjinniOptionalObjectHandle> DjinniMapInt32TString::fromCpp(std::optional<std::unordered_map<int32_t, std::string>> dc) {
    if (dc == std::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(DjinniMapInt32TString::fromCpp(std::move(* dc)), optional_map_int32_t_string___delete);
}

std::optional<std::unordered_map<int32_t, std::string>>DjinniMapInt32TString::toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh) {
     if (dh) {
        return std::optional<std::unordered_map<int32_t, std::string>>(DjinniMapInt32TString::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), map_int32_t_string___delete)));
    }
    return std::nullopt;
}

