// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "json_record.hpp"

#include "dh__json_record.hpp"
#include "dh__rc.hpp"
#include <optional>

static void(*s_py_callback_json_record___delete)(DjinniRecordHandle * );
void json_record_add_callback___delete(void(* ptr)(DjinniRecordHandle * )) {
    s_py_callback_json_record___delete = ptr;
}

void json_record___delete(DjinniRecordHandle * drh) {
    s_py_callback_json_record___delete(drh);
}
void optional_json_record___delete(DjinniOptionalRecordHandle * drh) {
    s_py_callback_json_record___delete((DjinniRecordHandle *) drh); // can't static cast, find better way
}
static DjinniOptionalRecordHandle * ( * s_py_callback_json_record_get_json_record_f1)(DjinniRecordHandle *);

void json_record_add_callback_get_json_record_f1(DjinniOptionalRecordHandle *( * ptr)(DjinniRecordHandle *)) {
    s_py_callback_json_record_get_json_record_f1 = ptr;
}

static DjinniRecordHandle * ( * s_py_callback_json_record_python_create_json_record)(DjinniOptionalRecordHandle *);

void json_record_add_callback_python_create_json_record(DjinniRecordHandle *( * ptr)(DjinniOptionalRecordHandle *)) {
    s_py_callback_json_record_python_create_json_record = ptr;
}

djinni::Handle<DjinniRecordHandle> DjinniJsonRecord::fromCpp(const ::textsort::JsonRecord& dr) {
    auto  _field_optional_rc = DjinniRc::fromCpp(dr.optional_rc);

    djinni::Handle<DjinniRecordHandle> _aux(
        s_py_callback_json_record_python_create_json_record(
            _field_optional_rc.release()),
        json_record___delete);
    return _aux;
}

::textsort::JsonRecord DjinniJsonRecord::toCpp(djinni::Handle<DjinniRecordHandle> dh) {
    djinni::Handle<DjinniOptionalRecordHandle> _field_optional_rc(s_py_callback_json_record_get_json_record_f1(dh.get()), optional_rc___delete);

    auto _aux = ::textsort::JsonRecord(
        DjinniRc::toCpp(std::move( _field_optional_rc)));
    return _aux;
}

djinni::Handle<DjinniOptionalRecordHandle> DjinniJsonRecord::fromCpp(std::optional<::textsort::JsonRecord> dc) {
    if (dc == std::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(DjinniJsonRecord::fromCpp(std::move(* dc)), optional_json_record___delete);
}

std::optional<::textsort::JsonRecord>DjinniJsonRecord::toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh) {
     if (dh) {
        return std::optional<::textsort::JsonRecord>(DjinniJsonRecord::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), json_record___delete)));
    }
    return std::nullopt;
}

