// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

struct DjinniBaseRecord;
void base_record___delete(struct DjinniRecordHandle * );
void optional_base_record___delete(struct DjinniOptionalRecordHandle * );
void base_record_add_callback_get_base_record_f1(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void base_record_add_callback_get_base_record_f2(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void base_record_add_callback_get_base_record_f3(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void base_record_add_callback_python_create_base_record(struct DjinniRecordHandle *( * ptr)(struct DjinniString *, struct DjinniString *, struct DjinniString *));
void base_record_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
