// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

struct DjinniHien;
void hien___delete(struct DjinniRecordHandle * );
void optional_hien___delete(struct DjinniOptionalRecordHandle * );
void hien_add_callback_get_hien_f1(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void hien_add_callback_get_hien_f2(struct DjinniString *( * ptr)(struct DjinniRecordHandle *));
void hien_add_callback_python_create_hien(struct DjinniRecordHandle *( * ptr)(struct DjinniString *, struct DjinniString *));
void hien_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
