// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

#include <stdint.h> // python_cdef_ignore

struct DjinniA;
void a___delete(struct DjinniRecordHandle * );
void optional_a___delete(struct DjinniOptionalRecordHandle * );
void a_add_callback_get_a_f1(uint8_t( * ptr)(struct DjinniRecordHandle *));
void a_add_callback_python_create_a(struct DjinniRecordHandle *( * ptr)(uint8_t));
void a_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
