// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "my_enum.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__my_enum.h"

#ifdef __cplusplus
}
#endif
int32_t int32_from_enum_my_enum(std::optional<::textsort::my_enum> e);
int32_t int32_from_enum_my_enum(::textsort::my_enum e);
std::optional<::textsort::my_enum> get_boxed_enum_my_enum_from_int32(int32_t e);
