// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "a.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__a.h"

#ifdef __cplusplus
}
#endif
struct DjinniA {
    static djinni::Handle<DjinniRecordHandle> fromCpp(const ::textsort::A& dr);
    static ::textsort::A toCpp(djinni::Handle<DjinniRecordHandle> dh);
    static djinni::Handle<DjinniOptionalRecordHandle> fromCpp(std::optional<::textsort::A> dc);
    static std::optional<::textsort::A> toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh);
};
