// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "a.hpp"

#include "dh__a.hpp"

static void(*s_py_callback_a___delete)(DjinniRecordHandle * );
void a_add_callback___delete(void(* ptr)(DjinniRecordHandle * )) {
    s_py_callback_a___delete = ptr;
}

void a___delete(DjinniRecordHandle * drh) {
    s_py_callback_a___delete(drh);
}
void optional_a___delete(DjinniOptionalRecordHandle * drh) {
    s_py_callback_a___delete((DjinniRecordHandle *) drh); // can't static cast, find better way
}
static uint8_t ( * s_py_callback_a_get_a_f1)(DjinniRecordHandle *);

void a_add_callback_get_a_f1(uint8_t( * ptr)(DjinniRecordHandle *)) {
    s_py_callback_a_get_a_f1 = ptr;
}

static DjinniRecordHandle * ( * s_py_callback_a_python_create_a)(uint8_t);

void a_add_callback_python_create_a(DjinniRecordHandle *( * ptr)(uint8_t)) {
    s_py_callback_a_python_create_a = ptr;
}

djinni::Handle<DjinniRecordHandle> DjinniA::fromCpp(const ::textsort::A& dr) {

    djinni::Handle<DjinniRecordHandle> _aux(
        s_py_callback_a_python_create_a(
            dr.h),
        a___delete);
    return _aux;
}

::textsort::A DjinniA::toCpp(djinni::Handle<DjinniRecordHandle> dh) {

    auto _aux = ::textsort::A(
        s_py_callback_a_get_a_f1(dh.get()));
    return _aux;
}

djinni::Handle<DjinniOptionalRecordHandle> DjinniA::fromCpp(std::optional<::textsort::A> dc) {
    if (dc == std::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(DjinniA::fromCpp(std::move(* dc)), optional_a___delete);
}

std::optional<::textsort::A>DjinniA::toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh) {
     if (dh) {
        return std::optional<::textsort::A>(DjinniA::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), a___delete)));
    }
    return std::nullopt;
}

