// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#include <iostream> // for debugging
#include <cassert>
#include "wrapper_marshal.hpp"
#include "my_record.hpp"

#include "dh__list_binary.hpp"
#include "dh__list_enum_my_enum.hpp"
#include "dh__list_record_rc.hpp"
#include "dh__list_uint32_t.hpp"
#include "dh__map_enum_my_enum_int16_t.hpp"
#include "dh__map_int32_t_string.hpp"
#include "dh__my_enum.hpp"
#include "dh__my_record.hpp"
#include "dh__rc.hpp"
#include "dh__set_enum_my_enum.hpp"
#include "dh__set_int32_t.hpp"
#include "my_enum.hpp"
#include <chrono>
#include <optional>
#include <vector>

static void(*s_py_callback_set_enum_my_enum___delete)(DjinniObjectHandle *);
void set_enum_my_enum_add_callback___delete(void(* ptr)(DjinniObjectHandle *)) {
    s_py_callback_set_enum_my_enum___delete = ptr;
}

void set_enum_my_enum___delete(DjinniObjectHandle * drh) {
    s_py_callback_set_enum_my_enum___delete(drh);
}
void optional_set_enum_my_enum___delete(DjinniOptionalObjectHandle *  drh) {
    s_py_callback_set_enum_my_enum___delete((DjinniObjectHandle *) drh);
}
static size_t ( * s_py_callback_set_enum_my_enum__get_size)(DjinniObjectHandle *);

void set_enum_my_enum_add_callback__get_size(size_t( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_set_enum_my_enum__get_size = ptr;
}

static DjinniObjectHandle * ( * s_py_callback_set_enum_my_enum__python_create)(void);

void set_enum_my_enum_add_callback__python_create(DjinniObjectHandle *( * ptr)(void)) {
    s_py_callback_set_enum_my_enum__python_create = ptr;
}

static void ( * s_py_callback_set_enum_my_enum__python_add)(DjinniObjectHandle *, int);

void set_enum_my_enum_add_callback__python_add(void( * ptr)(DjinniObjectHandle *, int)) {
    s_py_callback_set_enum_my_enum__python_add = ptr;
}

static int ( * s_py_callback_set_enum_my_enum__python_next)(DjinniObjectHandle *);

void set_enum_my_enum_add_callback__python_next(int( * ptr)(DjinniObjectHandle *)) {
    s_py_callback_set_enum_my_enum__python_next = ptr;
}

djinni::Handle<DjinniObjectHandle> DjinniSetEnumMyEnum::fromCpp(const std::unordered_set<::textsort::my_enum> & dc) {
    djinni::Handle<DjinniObjectHandle> _handle(s_py_callback_set_enum_my_enum__python_create(), & set_enum_my_enum___delete);
    for (const auto & it : dc) {
        s_py_callback_set_enum_my_enum__python_add(_handle.get(), int32_from_enum_my_enum(it));
    }

    return _handle;
}

std::unordered_set<::textsort::my_enum> DjinniSetEnumMyEnum::toCpp(djinni::Handle<DjinniObjectHandle> dh) {
    std::unordered_set<::textsort::my_enum>_ret;
    size_t size = s_py_callback_set_enum_my_enum__get_size(dh.get());

    for (int i = 0; i < size; i++) {
        auto _el = static_cast<::textsort::my_enum>(s_py_callback_set_enum_my_enum__python_next(dh.get()));
        _ret.insert(std::move(_el));
    }

    return _ret;
}

djinni::Handle<DjinniOptionalObjectHandle> DjinniSetEnumMyEnum::fromCpp(std::optional<std::unordered_set<::textsort::my_enum>> dc) {
    if (dc == std::nullopt) {
        return nullptr;
    }
    return djinni::optionals::toOptionalHandle(DjinniSetEnumMyEnum::fromCpp(std::move(* dc)), optional_set_enum_my_enum___delete);
}

std::optional<std::unordered_set<::textsort::my_enum>>DjinniSetEnumMyEnum::toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh) {
     if (dh) {
        return std::optional<std::unordered_set<::textsort::my_enum>>(DjinniSetEnumMyEnum::toCpp(djinni::optionals::fromOptionalHandle(std::move(dh), set_enum_my_enum___delete)));
    }
    return std::nullopt;
}

