// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once // python_cdef_ignore
#include <stdbool.h>  // python_cdef_ignore

struct DjinniJsonRecord;
void json_record___delete(struct DjinniRecordHandle * );
void optional_json_record___delete(struct DjinniOptionalRecordHandle * );
void json_record_add_callback_get_json_record_f1(struct DjinniOptionalRecordHandle *( * ptr)(struct DjinniRecordHandle *));
void json_record_add_callback_python_create_json_record(struct DjinniRecordHandle *( * ptr)(struct DjinniOptionalRecordHandle *));
void json_record_add_callback___delete(void( * ptr)(struct DjinniRecordHandle *));
