// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "my_record.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__map_int32_t_string.h"

#ifdef __cplusplus
}
#endif
struct DjinniMapInt32TString {
    static djinni::Handle<DjinniObjectHandle> fromCpp(const std::unordered_map<int32_t, std::string> & dc);
    static std::unordered_map<int32_t, std::string> toCpp(djinni::Handle<DjinniObjectHandle> dh);
    static djinni::Handle<DjinniOptionalObjectHandle>fromCpp(std::optional<std::unordered_map<int32_t, std::string>> dc);
    static std::optional<std::unordered_map<int32_t, std::string>> toCpp(djinni::Handle<DjinniOptionalObjectHandle> dh);
};
