// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <atomic>
#include <optional>
#include "rc.hpp"
#ifdef __cplusplus
extern "C" {
#endif

#include "dh__rc.h"

#ifdef __cplusplus
}
#endif
struct DjinniRc {
    static djinni::Handle<DjinniRecordHandle> fromCpp(const ::cpp_generated::Rc& dr);
    static ::cpp_generated::Rc toCpp(djinni::Handle<DjinniRecordHandle> dh);
    static djinni::Handle<DjinniOptionalRecordHandle> fromCpp(std::optional<::cpp_generated::Rc> dc);
    static std::optional<::cpp_generated::Rc> toCpp(djinni::Handle<DjinniOptionalRecordHandle> dh);
};
