fastlane_version "2.70.1"
default_platform :ios

def get_libary_version
    return '4.6.0'
end

lane :submit_podspecs do

    version_bump_podspec(path: "DjinniSwift.podspec", version_number: get_libary_version)
    version_bump_podspec(path: "Djinni.podspec", version_number: get_libary_version)

    pod_push(path: "DjinniSwift.podspec",
        repo: "misfit-podspecs",
        allow_warnings: true,
        verbose: true)

    pod_push(path: "Djinni.podspec",
        repo: "misfit-podspecs",
        allow_warnings: true,
        skip_import_validation: true,
        verbose: true)
end

