// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include <functional>

namespace cpp_generated {

enum class MyEnum : int {
    HIEN ,
    A ,
    B ,
};

}  // namespace cpp_generated

namespace std {

template <>
struct hash<::cpp_generated::MyEnum> {
    size_t operator()(::cpp_generated::MyEnum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
