// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

// Demo.h
// Demo

#import <Foundation/Foundation.h>

//! Project version number for Demo.
FOUNDATION_EXPORT double DemoVersionNumber;

//! Project version string for Demo.
FOUNDATION_EXPORT const unsigned char DemoVersionString[];

#import "MyEnum.h"
#import "Hello.h"
