// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>
typedef enum MyEnum: NSInteger MyEnum;
@class MyRecord;
@class Hello;
#import <Foundation/Foundation.h>


NS_SWIFT_NAME(Hello)
@interface Hello : NSObject

- (nonnull instancetype)init NS_UNAVAILABLE;

+ (nonnull Hello *)create;

- (MyEnum)sayHi;

- (nonnull MyRecord *)print:(nonnull MyRecord *)rc;

@end
