// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ class A {


    /*package*/ final short mH;

    public A(
            short h) {
        this.mH = h;
    }

    public short getH() {
        return mH;
    }

    @Override
    public String toString() {
        return "A{" +
                "mH=" + mH +
        "}";
    }

}
