// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ class BaseRecord extends Hien {


    /*package*/ final String mParent;

    public BaseRecord(
            @Nonnull String hien,
            @Nonnull String hien1,
            @Nonnull String parent) {
        super(hien,hien1);
        this.mParent = parent;
    }

    @Nonnull
    public String getParent() {
        return mParent;
    }

    @Override
    public String toString() {
        return "BaseRecord{" +
                "mHien=" + mHien +
                "," + "mHien1=" + mHien1 +
                "," + "mParent=" + mParent +
        "}";
    }

}
