// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ class Hien {


    /*package*/ final String mHien;

    /*package*/ final String mHien1;

    public Hien(
            @Nonnull String hien,
            @Nonnull String hien1) {
        this.mHien = hien;
        this.mHien1 = hien1;
    }

    @Nonnull
    public String getHien() {
        return mHien;
    }

    @Nonnull
    public String getHien1() {
        return mHien1;
    }

    @Override
    public String toString() {
        return "Hien{" +
                "mHien=" + mHien +
                "," + "mHien1=" + mHien1 +
        "}";
    }

}
