// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ class JsonRecord {


    /*package*/ final Rc mOptionalRc;

    public JsonRecord(
            @CheckForNull Rc optionalRc) {
        this.mOptionalRc = optionalRc;
    }

    @CheckForNull
    public Rc getOptionalRc() {
        return mOptionalRc;
    }

    @Override
    public String toString() {
        return "JsonRecord{" +
                "mOptionalRc=" + mOptionalRc +
        "}";
    }

}
