// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ class MyRecord {


    /*package*/ final int mTest;

    /*package*/ final Integer mTest1;

    /*package*/ final ArrayList<Integer> mTest2;

    /*package*/ final String mTest3;

    /*package*/ final String mTest31;

    /*package*/ final Date mTest4;

    /*package*/ final Date mTest41;

    /*package*/ final byte[] mTest5;

    /*package*/ final ArrayList<byte[]> mTest6;

    /*package*/ final HashSet<Integer> mTest7;

    /*package*/ final HashMap<Integer, String> mTest8;

    /*package*/ final Rc mTest9;

    /*package*/ final Rc mTest10;

    /*package*/ final ArrayList<Rc> mTest101;

    /*package*/ final MyEnum mTest11;

    /*package*/ final org.json.JSONObject mTest12;

    /*package*/ final MyEnum mTest13;

    /*package*/ final Short mTest14;

    /*package*/ final ArrayList<MyEnum> mTest15;

    /*package*/ final HashSet<MyEnum> mTest16;

    /*package*/ final HashMap<MyEnum, Short> mTest17;

    public MyRecord(
            int test,
            @CheckForNull Integer test1,
            @Nonnull ArrayList<Integer> test2,
            @Nonnull String test3,
            @CheckForNull String test31,
            @Nonnull Date test4,
            @CheckForNull Date test41,
            @Nonnull byte[] test5,
            @Nonnull ArrayList<byte[]> test6,
            @Nonnull HashSet<Integer> test7,
            @Nonnull HashMap<Integer, String> test8,
            @Nonnull Rc test9,
            @CheckForNull Rc test10,
            @Nonnull ArrayList<Rc> test101,
            @Nonnull MyEnum test11,
            @Nonnull org.json.JSONObject test12,
            @CheckForNull MyEnum test13,
            @CheckForNull Short test14,
            @Nonnull ArrayList<MyEnum> test15,
            @Nonnull HashSet<MyEnum> test16,
            @Nonnull HashMap<MyEnum, Short> test17) {
        this.mTest = test;
        this.mTest1 = test1;
        this.mTest2 = test2;
        this.mTest3 = test3;
        this.mTest31 = test31;
        this.mTest4 = test4;
        this.mTest41 = test41;
        this.mTest5 = test5;
        this.mTest6 = test6;
        this.mTest7 = test7;
        this.mTest8 = test8;
        this.mTest9 = test9;
        this.mTest10 = test10;
        this.mTest101 = test101;
        this.mTest11 = test11;
        this.mTest12 = test12;
        this.mTest13 = test13;
        this.mTest14 = test14;
        this.mTest15 = test15;
        this.mTest16 = test16;
        this.mTest17 = test17;
    }

    public int getTest() {
        return mTest;
    }

    @CheckForNull
    public Integer getTest1() {
        return mTest1;
    }

    @Nonnull
    public ArrayList<Integer> getTest2() {
        return mTest2;
    }

    @Nonnull
    public String getTest3() {
        return mTest3;
    }

    @CheckForNull
    public String getTest31() {
        return mTest31;
    }

    @Nonnull
    public Date getTest4() {
        return mTest4;
    }

    @CheckForNull
    public Date getTest41() {
        return mTest41;
    }

    @Nonnull
    public byte[] getTest5() {
        return mTest5;
    }

    @Nonnull
    public ArrayList<byte[]> getTest6() {
        return mTest6;
    }

    @Nonnull
    public HashSet<Integer> getTest7() {
        return mTest7;
    }

    @Nonnull
    public HashMap<Integer, String> getTest8() {
        return mTest8;
    }

    @Nonnull
    public Rc getTest9() {
        return mTest9;
    }

    @CheckForNull
    public Rc getTest10() {
        return mTest10;
    }

    @Nonnull
    public ArrayList<Rc> getTest101() {
        return mTest101;
    }

    @Nonnull
    public MyEnum getTest11() {
        return mTest11;
    }

    @Nonnull
    public org.json.JSONObject getTest12() {
        return mTest12;
    }

    @CheckForNull
    public MyEnum getTest13() {
        return mTest13;
    }

    @CheckForNull
    public Short getTest14() {
        return mTest14;
    }

    @Nonnull
    public ArrayList<MyEnum> getTest15() {
        return mTest15;
    }

    @Nonnull
    public HashSet<MyEnum> getTest16() {
        return mTest16;
    }

    @Nonnull
    public HashMap<MyEnum, Short> getTest17() {
        return mTest17;
    }

    @Override
    public String toString() {
        return "MyRecord{" +
                "mTest=" + mTest +
                "," + "mTest1=" + mTest1 +
                "," + "mTest2=" + mTest2 +
                "," + "mTest3=" + mTest3 +
                "," + "mTest31=" + mTest31 +
                "," + "mTest4=" + mTest4 +
                "," + "mTest41=" + mTest41 +
                "," + "mTest5=" + mTest5 +
                "," + "mTest6=" + mTest6 +
                "," + "mTest7=" + mTest7 +
                "," + "mTest8=" + mTest8 +
                "," + "mTest9=" + mTest9 +
                "," + "mTest10=" + mTest10 +
                "," + "mTest101=" + mTest101 +
                "," + "mTest11=" + mTest11 +
                "," + "mTest12=" + mTest12 +
                "," + "mTest13=" + mTest13 +
                "," + "mTest14=" + mTest14 +
                "," + "mTest15=" + mTest15 +
                "," + "mTest16=" + mTest16 +
                "," + "mTest17=" + mTest17 +
        "}";
    }

}
