// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ class Rc {


    /*package*/ final int mA;

    public Rc(
            int a) {
        this.mA = a;
    }

    public int getA() {
        return mA;
    }

    @Override
    public String toString() {
        return "Rc{" +
                "mA=" + mA +
        "}";
    }

}
