// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import javax.annotation.CheckForNull;
import javax.annotation.Nonnull;

/*package*/ enum SortOrder {
    ASCENDING(1),
    DESCENDING(3),
    RANDOM(4),
    ;
    private final int value;
    private SortOrder(int value) {
        this.value = value;
    }
    public int getValue() {
        return this.value;
    }
}
