// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

extension A  {
    @available(swift, obsoleted: 1.0)
    @objc public var __djinni__objc_h: UInt8 {
        get {
            return h
        }
    }
    @available(swift, obsoleted: 1.0)
    @objc public static func `init`(h: UInt8) -> A {
        return A.init(h: h)}
}
