// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

@objc public class A : NSObject {

    public let h : UInt8

    public init(h: UInt8) {
        self.h = h
    }
}
