// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni

// DjinniExample.h
// DjinniExample

#import <Foundation/Foundation.h>

//! Project version number for DjinniExample.
FOUNDATION_EXPORT double DjinniExampleVersionNumber;

//! Project version string for DjinniExample.
FOUNDATION_EXPORT const unsigned char DjinniExampleVersionString[];

