// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

@objc public class JsonRecord : NSObject {

    public let optionalRc : Rc?

    public init(optionalRc: Rc?) {
        self.optionalRc = optionalRc
    }
}
