// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

extension JsonRecord  {
    @available(swift, obsoleted: 1.0)
    @objc public var __djinni__objc_optionalRc: Rc? {
        get {
            return optionalRc
        }
    }
    @available(swift, obsoleted: 1.0)
    @objc public static func `init`(optionalRc: Rc?) -> JsonRecord {
        return JsonRecord.init(optionalRc: optionalRc)}
}
