// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

typedef NS_CLOSED_ENUM(NSInteger, MyEnum)
{
    MyEnumHien  = 1,
    MyEnumWorkout ,
    MyEnumRunning ,
} NS_SWIFT_NAME(MyEnum);
