// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSInteger, MyEnum)
{
    MyEnumHien  = 1,
    MyEnumA ,
    MyEnumB ,
} NS_SWIFT_NAME(MyEnum);
