// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

@objc public class MyRecord : NSObject {

    public let test : Int32

    public let test1 : UInt32?

    public let test2 : Array<UInt32>

    public let test3 : String

    public let test31 : String?

    public let test4 : Date

    public let test41 : Date?

    public let test5 : Data

    public let test6 : Array<Data>

    public let test7 : Set<Int32>

    public let test8 : Dictionary<Int32, String>

    public let test9 : Rc

    public let test10 : Rc?

    public let test101 : Array<Rc>

    public let test11 : MyEnum

    public let test13 : MyEnum?

    public let test14 : Int16?

    public let test15 : Array<MyEnum>

    public let test16 : Set<MyEnum>

    public let test17 : Dictionary<MyEnum, Int16>

    public init(test: Int32,
                test1: UInt32?,
                test2: Array<UInt32>,
                test3: String,
                test31: String?,
                test4: Date,
                test41: Date?,
                test5: Data,
                test6: Array<Data>,
                test7: Set<Int32>,
                test8: Dictionary<Int32, String>,
                test9: Rc,
                test10: Rc?,
                test101: Array<Rc>,
                test11: MyEnum,
                test13: MyEnum?,
                test14: Int16?,
                test15: Array<MyEnum>,
                test16: Set<MyEnum>,
                test17: Dictionary<MyEnum, Int16>) {
        self.test = test
        self.test1 = test1
        self.test2 = test2
        self.test3 = test3
        self.test31 = test31
        self.test4 = test4
        self.test41 = test41
        self.test5 = test5
        self.test6 = test6
        self.test7 = test7
        self.test8 = test8
        self.test9 = test9
        self.test10 = test10
        self.test101 = test101
        self.test11 = test11
        self.test13 = test13
        self.test14 = test14
        self.test15 = test15
        self.test16 = test16
        self.test17 = test17
    }
}
