// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

@objc public class Rc : NSObject {

    public let a : Int32

    public init(a: Int32) {
        self.a = a
    }
}
