// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

import DjinniSwift
import Foundation

@objc public class Rc : NSObject {

    public let a : Int32

    public let b : Int32

    public let c : Int32?

    public let d : MyEnum

    public let e : Data

    public init(a: Int32,
                b: Int32,
                c: Int32?,
                d: MyEnum,
                e: Data) {
        self.a = a
        self.b = b
        self.c = c
        self.d = d
        self.e = e
    }
}
