# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from example.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files
from djinni.pycffi_marshal import CPyRecord, CPyString

from hien import Hien
from hien_helper import HienHelper
from PyCFFIlib_cffi import ffi, lib

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

class BaseRecord(Hien):
    c_data_set = MultiSet()

    @staticmethod
    def check_c_data_set_empty():
        assert len(BaseRecord.c_data_set) == 0


    def __init__(self, hien, hien_1, parent):
        super().__init__(hien, hien_1)
        self.parent = parent

    def __str__(self):
        return "BaseRecord{" +
                "hien=" + hien +
                "," + "hien_1=" + hien_1 +
                "," + "parent=" + parent +
        "}"

