# AUTOGENERATED FILE - DO NOT MODIFY!
# This file generated by Djinni from example.djinni

from djinni.support import MultiSet # default imported in all files
from djinni.exception import CPyException # default imported in all files

from djinni import exception # this forces run of __init__.py which gives cpp option to call back into py to create exception

from enum import IntEnum, unique

@unique
class MyEnum(IntEnum):
    Hien = 0
    A = 1
    B = 2
